name: Railway Deployment # a name for your workflow

on: # trigger on push event and main branch to the repo
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm i

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service therapy-front
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}