on: # trigger on push event and main branch to the repo
  push:
    branches: [main]
    workflow_dispatch: # must be included in your .yml file for manually triggering event
    # defaults: # in case of monorepo project you can use `defauls` and choose the subfolder
    #   run:
    #     working-directory: ./gatsbyJS

# Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service therapy-front
        env:
          RAILWAY_TOKEN: ba35e093-04ef-4470-8d07-eedc61439de9